name: create new release
on:
  pull_request:
    types: [ closed ]
jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: release-drafter/release-drafter@v5
        with:
          config-name: config/relese-config.yml
          disable-autolabeler: true
          publish: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}