name: releases and publish
on:

  pull_request:
    types: [ closed ]
    
jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: release-drafter/release-drafter@v5
        with:
          config-name: config/relese-config.yml
          disable-autolabeler: true
          publish: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-project:
    needs: update_release_draft
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm i
      - run: npm run build

  publish-npm:
    needs: build-project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm publish 
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          