name: testing
on:
  pull_request:
    types: [opened, edited, reopened, synchronize]
jobs:
  check-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          title-regex: "#[eE][xX]-[0-9]+"
          on-failed-regex-fail-action: false
          on-failed-regex-request-changes: false
          on-failed-regex-create-review: true
          on-failed-regex-comment:
            "something went wrong: `%regex%`!"
          on-succeeded-regex-dismiss-review-comment:
            "Done, Success!"
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
      - run: npm install
      - run: npm run test